import SwiftUI
import TrainingCore

/// Native paths transcribed from the approved 96 × 128 SVG concepts.
struct ProgramChoiceIcon: View {
    let choice: StarterProgramChoice
    var body: some View {
        GeometryReader { geometry in
            Figure(choice: choice)
                .stroke(style: StrokeStyle(lineWidth: 2.7 * min(geometry.size.width / 96, geometry.size.height / 128), lineCap: .round, lineJoin: .round))
        }
            .aspectRatio(96.0 / 128.0, contentMode: .fit)
            .accessibilityHidden(true)
    }
    private struct Figure: Shape {
        let choice: StarterProgramChoice
        func path(in rect: CGRect) -> Path {
            var p = Path()
            p.addEllipse(in: CGRect(x: 39, y: 4, width: 18, height: 18))
            if choice == .upperBody {
                p.move(to: CGPoint(x: 42, y: 22))
                p.addLine(to: CGPoint(x: 42, y: 27))
                p.move(to: CGPoint(x: 54, y: 22))
                p.addLine(to: CGPoint(x: 54, y: 27))
                p.move(to: CGPoint(x: 42, y: 27))
                p.addCurve(to: CGPoint(x: 20, y: 32), control1: CGPoint(x: 32, y: 25), control2: CGPoint(x: 24, y: 26))
                p.addLine(to: CGPoint(x: 11, y: 47))
                p.addCurve(to: CGPoint(x: 16, y: 60), control1: CGPoint(x: 8, y: 53), control2: CGPoint(x: 11, y: 59))
                p.addLine(to: CGPoint(x: 26, y: 44))
                p.move(to: CGPoint(x: 54, y: 27))
                p.addCurve(to: CGPoint(x: 76, y: 32), control1: CGPoint(x: 64, y: 25), control2: CGPoint(x: 72, y: 26))
                p.addLine(to: CGPoint(x: 85, y: 47))
                p.addCurve(to: CGPoint(x: 80, y: 60), control1: CGPoint(x: 88, y: 53), control2: CGPoint(x: 85, y: 59))
                p.addLine(to: CGPoint(x: 70, y: 44))
                p.move(to: CGPoint(x: 25, y: 35))
                p.addCurve(to: CGPoint(x: 37, y: 69), control1: CGPoint(x: 29, y: 47), control2: CGPoint(x: 33, y: 58))
                p.addLine(to: CGPoint(x: 59, y: 69))
                p.addCurve(to: CGPoint(x: 71, y: 35), control1: CGPoint(x: 63, y: 58), control2: CGPoint(x: 67, y: 47))
                p.move(to: CGPoint(x: 29, y: 41))
                p.addCurve(to: CGPoint(x: 48, y: 40), control1: CGPoint(x: 35, y: 43), control2: CGPoint(x: 41, y: 43))
                p.addCurve(to: CGPoint(x: 67, y: 41), control1: CGPoint(x: 55, y: 43), control2: CGPoint(x: 61, y: 43))
                p.move(to: CGPoint(x: 48, y: 41))
                p.addLine(to: CGPoint(x: 48, y: 65))
                p.move(to: CGPoint(x: 39, y: 51))
                p.addLine(to: CGPoint(x: 44, y: 53))
                p.move(to: CGPoint(x: 57, y: 51))
                p.addLine(to: CGPoint(x: 52, y: 53))
                p.move(to: CGPoint(x: 41, y: 61))
                p.addLine(to: CGPoint(x: 45, y: 61))
                p.move(to: CGPoint(x: 55, y: 61))
                p.addLine(to: CGPoint(x: 51, y: 61))
                p.move(to: CGPoint(x: 37, y: 69))
                p.addLine(to: CGPoint(x: 33, y: 85))
                p.addLine(to: CGPoint(x: 45, y: 90))
                p.addLine(to: CGPoint(x: 48, y: 80))
                p.addLine(to: CGPoint(x: 51, y: 90))
                p.addLine(to: CGPoint(x: 63, y: 85))
                p.addLine(to: CGPoint(x: 59, y: 69))
                p.move(to: CGPoint(x: 35, y: 87))
                p.addLine(to: CGPoint(x: 37, y: 108))
                p.addLine(to: CGPoint(x: 34, y: 121))
                p.addLine(to: CGPoint(x: 44, y: 121))
                p.addLine(to: CGPoint(x: 47, y: 89))
                p.move(to: CGPoint(x: 61, y: 87))
                p.addLine(to: CGPoint(x: 59, y: 108))
                p.addLine(to: CGPoint(x: 62, y: 121))
                p.addLine(to: CGPoint(x: 52, y: 121))
                p.addLine(to: CGPoint(x: 49, y: 89))
                p.move(to: CGPoint(x: 14, y: 48))
                p.addLine(to: CGPoint(x: 20, y: 50))
                p.move(to: CGPoint(x: 82, y: 48))
                p.addLine(to: CGPoint(x: 76, y: 50))
            } else {
                p.move(to: CGPoint(x: 40, y: 8))
                p.addCurve(to: CGPoint(x: 35, y: 22), control1: CGPoint(x: 34, y: 10), control2: CGPoint(x: 32, y: 16))
                p.move(to: CGPoint(x: 42, y: 22))
                p.addLine(to: CGPoint(x: 42, y: 27))
                p.move(to: CGPoint(x: 54, y: 22))
                p.addLine(to: CGPoint(x: 54, y: 27))
                p.move(to: CGPoint(x: 42, y: 27))
                p.addLine(to: CGPoint(x: 31, y: 32))
                p.addCurve(to: CGPoint(x: 24, y: 50), control1: CGPoint(x: 27, y: 35), control2: CGPoint(x: 25, y: 42))
                p.addLine(to: CGPoint(x: 20, y: 67))
                p.addCurve(to: CGPoint(x: 25, y: 73), control1: CGPoint(x: 19, y: 71), control2: CGPoint(x: 22, y: 74))
                p.addLine(to: CGPoint(x: 31, y: 50))
                p.move(to: CGPoint(x: 54, y: 27))
                p.addLine(to: CGPoint(x: 65, y: 32))
                p.addCurve(to: CGPoint(x: 72, y: 50), control1: CGPoint(x: 69, y: 35), control2: CGPoint(x: 71, y: 42))
                p.addLine(to: CGPoint(x: 76, y: 67))
                p.addCurve(to: CGPoint(x: 71, y: 73), control1: CGPoint(x: 77, y: 71), control2: CGPoint(x: 74, y: 74))
                p.addLine(to: CGPoint(x: 65, y: 50))
                p.move(to: CGPoint(x: 34, y: 33))
                p.addLine(to: CGPoint(x: 37, y: 42))
                p.move(to: CGPoint(x: 62, y: 33))
                p.addLine(to: CGPoint(x: 59, y: 42))
                p.move(to: CGPoint(x: 35, y: 42))
                p.addCurve(to: CGPoint(x: 41, y: 59), control1: CGPoint(x: 37, y: 48), control2: CGPoint(x: 40, y: 53))
                p.addLine(to: CGPoint(x: 55, y: 59))
                p.addCurve(to: CGPoint(x: 61, y: 42), control1: CGPoint(x: 56, y: 53), control2: CGPoint(x: 59, y: 48))
                p.move(to: CGPoint(x: 35, y: 42))
                p.addLine(to: CGPoint(x: 61, y: 42))
                p.move(to: CGPoint(x: 41, y: 59))
                p.addCurve(to: CGPoint(x: 30, y: 76), control1: CGPoint(x: 40, y: 66), control2: CGPoint(x: 34, y: 69))
                p.addCurve(to: CGPoint(x: 31, y: 96), control1: CGPoint(x: 27, y: 82), control2: CGPoint(x: 28, y: 90))
                p.addLine(to: CGPoint(x: 38, y: 121))
                p.addLine(to: CGPoint(x: 47, y: 121))
                p.addLine(to: CGPoint(x: 46, y: 94))
                p.addLine(to: CGPoint(x: 48, y: 82))
                p.addLine(to: CGPoint(x: 50, y: 94))
                p.addLine(to: CGPoint(x: 49, y: 121))
                p.addLine(to: CGPoint(x: 58, y: 121))
                p.addLine(to: CGPoint(x: 65, y: 96))
                p.addCurve(to: CGPoint(x: 66, y: 76), control1: CGPoint(x: 68, y: 90), control2: CGPoint(x: 69, y: 82))
                p.addCurve(to: CGPoint(x: 55, y: 59), control1: CGPoint(x: 62, y: 69), control2: CGPoint(x: 56, y: 66))
                p.move(to: CGPoint(x: 33, y: 70))
                p.addCurve(to: CGPoint(x: 63, y: 70), control1: CGPoint(x: 42, y: 73), control2: CGPoint(x: 54, y: 73))
                p.move(to: CGPoint(x: 31, y: 96))
                p.addLine(to: CGPoint(x: 39, y: 98))
                p.move(to: CGPoint(x: 65, y: 96))
                p.addLine(to: CGPoint(x: 57, y: 98))
            }
            let scale = min(rect.width / 96, rect.height / 128)
            return p.applying(CGAffineTransform(scaleX: scale, y: scale))
                .applying(CGAffineTransform(translationX: rect.midX - 48 * scale, y: rect.midY - 64 * scale))
        }
    }
}
